### ISSUE TITLE
Mob Pathing Implementation

### ISSUE THREAD

**Issue by n0remac** [n0remac/game-jam-2020#14]
A floor_list will be maintained somewhere. This can used for the matrix that monster will be pathed across. Rather than have every mob constantly pathing to the player or checking if the player is in range it might make more sense to have the player constantly checking a certain diameter for enemies. Enemies in that diameter will then path to the player if they are in range. ie the location of the player will dictate which enemies are active.

**Comment by Xevion** [comment]
I'd like to assist with this when possible by implementing multiple modules. I have a couple ideas for ways to speed the pathing algorithms up, or scaling them back just enough so that they aren't an detriment to the game. Will start tomorrow, along with the GUI. I'll see whatever you've got and build/refactor off that.
